# Generated by Django 2.0.6 on 2018-06-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0002_album_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_lowres',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
