# Generated by Django 2.0.6 on 2018-06-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0004_auto_20180618_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default='fancy', max_length=30),
            preserve_default=False,
        ),
    ]
