# Generated by Django 2.0.3 on 2018-06-24 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0005_album_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='time_made',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='photo',
            name='shot_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
