# Generated by Django 2.0.3 on 2018-06-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0006_auto_20180624_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
