# Generated by Django 2.0.6 on 2018-07-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0007_album_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
