# Generated by Django 2.0.6 on 2018-07-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0008_auto_20180721_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_full_size_image_on_capture', models.BooleanField(default=True)),
                ('do_countdown', models.BooleanField(default=False)),
            ],
        ),
    ]
