# Generated by Django 2.0.6 on 2018-07-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0009_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='number_in_album',
            field=models.IntegerField(default=0),
        ),
    ]
