# Generated by Django 2.0.6 on 2018-07-24 22:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0010_photo_number_in_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='album',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
