# Generated by Django 2.0.6 on 2018-07-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0011_auto_20180725_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-priority', '-last_modified']},
        ),
    ]
