# Generated by Django 2.0.6 on 2018-07-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0013_auto_20180731_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(default='', verbose_name='Beskrivelse'),
        ),
    ]
