# Generated by Django 2.0.6 on 2018-07-31 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0015_auto_20180731_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='main_album',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='remote.Album'),
        ),
    ]
